### ISSUE TITLE
Can not enter any keyword when keyboard using a language is different from English

### ISSUE THREAD

**Issue by ngocdb** [pichillilorenzo/flutter_browser_app#3]
Hi, thank you for your great apps & in app webview flutter plugin.

The apps work well on my phone when I use English on my keyboard.
![Screenshot_20200923-150141](https://user-images.githubusercontent.com/3035559/93984899-9722d280-fdae-11ea-81df-5dcd75b3d107.jpg)

But no input when I type using another language, e.g Vietnamese in my case.
![Screenshot_20200923-150124](https://user-images.githubusercontent.com/3035559/93984904-98ec9600-fdae-11ea-8151-a07341d7aedc.jpg)

I checked & there is the same issue if I use the in app webview plugin in my apps (to test)

Is there any chance to get it fixed?

Thank you a lot.

**Comment by nurulayni** [comment]
Awesome , Have you ever tried to add dns in your browser, is it possible to dns in the browser bro ?

**Comment by pichillilorenzo** [comment]
fix with latest release
