### ISSUE TITLE
Lags when multiple tabs are opened

### ISSUE THREAD

**Issue by sukhcha-in** [pichillilorenzo/flutter_browser_app#4]
## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |       GooglePlayDemo        |
| App version          |       Latest        |
| Android version      |       10        |
| iOS version          |               |
| Xcode version        |               |

Device information: Samsung Galaxy M30s

## Description

**Expected behavior:** 
Should work smoothly when opened multiple tabs

**Current behavior:** 
Lags when 5-6 tabs are opened

## Steps to reproduce

Just open multiple tabs

**Comment by pichillilorenzo** [comment]
Yeah, I know. Flutter PlatformView on Android is not good as on iOS, unfortunately.
However, I'm working to update it with the latest version of flutter_inappwebview plugin using Hybrid Composition for Android >= 10 that will have better performance.
One problem is that on devices with < Android 10, Hybrid Composition causes bad performance on Flutter animations (https://github.com/flutter/flutter/wiki/Hybrid-Composition#performance)

**Comment by pichillilorenzo** [comment]
It should be ok with latest release!
